site_name: Tor Network Dataset
site_url: http://www.indexoffy.com/
repo_name: IndexOffy/tor-network-dataset
repo_url: https://github.com/IndexOffy/tor-network-dataset

nav:
    - Home: index.md
    - Info: nav/info.md
    - Graphic: nav/graphic.md
    - Development:
      - nav/development/development-guide.md
      - nav/development/release-notes.md

theme: 
    name: simple-blog
    logo: assets/logo.jpeg
